### PR TITLE
Team 5-Signoff-Resistance 

### PR DESCRIPTION
**Pull request by jay-marcom**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
I don't really see a design here.

**Comment by crozenboom** [comment]
Requesting review for revision 1.

**Comment by crozenboom** [comment]
Unsure of subsystem direction validity. Need confirmation. Specific feedback?

**Comment by crozenboom** [comment]
Requesting feedback for Resistance System sign-off.

**Review by JesseTNRoberts — COMMENTED** [review]
Request feedback when the design is completed. Otherwise, it may change and there's no need for a formal review.

**Comment by crozenboom** [comment]
Requesting review for resistance subsystem signoff.

**Comment by crozenboom** [comment]
Requesting review for resistance system signoff

**Review by JesseTNRoberts — COMMENTED** [review]
I won't sign off on this until you can explain the graphs and what they mean and why they are represented the way they are.

**Review by JesseTNRoberts — COMMENTED** [review]
Electrical schematic for the sensor is insufficient. Also, where is the sensor in the 3d schematic?

**Comment by crozenboom** [comment]
I implemented your desired changes. If there is anything else you think is missing, please let me know. Otherwise, requesting signoff for resistance system.

**Review by JesseTNRoberts — COMMENTED** [review]
Explain why the work is a dotted line.
It doesn't look like the sensor is going to sit well on the pedal.

This communicates via?

**Comment by crozenboom** [comment]
Requesting Signoff for Resistance System.

**Review by JesseTNRoberts — COMMENTED** [review]
So, now I suppose my question is, why is the actuator taking so long to reach the set point? I would expect it to have a bit of overshoot and take a second to reach the destination, but this is far too long. Remember, your work gives you the set point and your distance is the thing being controlled. 

Everything else looks good to me and modeling the dynamics of the control system is beyond my expectations. But be aware that in implementation you'll need to use a PID to control the actuator distance.

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
