### PR TITLE
Team5-Signoff-GUISystem

### PR DESCRIPTION
**Pull request by Baebel43**
Requesting signoff for the GUI Subsystem

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
How do we know that that the delay between a tap and the screen response will be less than 300ms?

**Review by JesseTNRoberts — COMMENTED** [review]
What sort of software is necessary to do this? How do we know that the screen/system can do what you intend it to do?

The analysis section doesn't prove that it will/can do what you intend.

**Comment by Baebel43** [comment]
Requesting Signoff for Revisions 2 of the GUI subsystem

**Review by JesseTNRoberts — COMMENTED** [review]
Since this is the gui design signoff, I think there should be more constraints regarding best practices for gui design. What makes a good gui beyond minimal delay?

**Pull request merged**
