### PR TITLE
Team5 signoff immersion

### PR DESCRIPTION
**Pull request by xELFHEROx**
Requesting Signoff  for Immersion Subsystem

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
In person comments

**Review by JesseTNRoberts — COMMENTED** [review]
We discussed that mapping to an RPM does not make sense. You need to map outside wind speed to generated wind speed.

**Comment by xELFHEROx** [comment]
> We discussed that mapping to an RPM does not make sense. You need to map outside wind speed to generated wind speed.

I believe that what I did may have been misunderstood. The RPM of the fans is mapped to the force the force value that was calculated through the wind pressure and and drag coefficient calculations. So as the force the force that the user experiences from wind exponentially increases, so does the RPM of the fans as well. This is also shown in the relative CFM values in the table. At lower mph there is a much smaller increase in cfm and rpm, and at higher speeds there is a much larger increase per mph. Please let me know if this needs further explaining or anything else. Thanks!

**Comment by JesseTNRoberts** [comment]
I want a linear relationship between outdoor wind speed and simulated wind speed. I'm unclear why we need to discuss pressure.

**Comment by xELFHEROx** [comment]
> I want a linear relationship between outdoor wind speed and simulated wind speed. I'm unclear why we need to discuss pressure.

When you are riding out on a physical trail, the movement of the air around you does not start to speed up. As you increase in speed your body and bike start to have more resistance against the wind. This is why the strength of the wind starts to become exponentially stronger at higher speeds. This is because the wind load is found by how much drag an object has and the wind pressure, which is a product of the objects velocity squared. 

The wind load becomes stronger because you are moving against it and creating drag and resistance. In a simulation though where the user is in one position, there is no longer any pressure from the wind as you move forward so in order to simulate that feeling of the pressure/force increase with speed increase in some scale, the speed of the fans has to move even faster to try and match the force of the wind instead of its speed. Moving 30mph through the wind is going to be a lot more intense than having a fan that is blowing on you at 30mph.

**Comment by JesseTNRoberts** [comment]
"When you are riding out on a physical trail, the movement of the air around you does not start to speed up." - Incorrect.

The air around you is considered stationary. You are moving. Therefore, the air around you has a speed equal to your velocity if measured from your reference frame. Changing your velocity results in an apparent change in wind speed.

**Comment by JesseTNRoberts** [comment]
As the customer, I do not care about wind load. I care about wind speed.

**Review by JesseTNRoberts — COMMENTED** [review]
I have made clear that force of wind is not something that I am interested in. Further, I have made clear that proportional RPM to wind speed is not correct. 

As an engineer, your job is to understand the expectations of your stakeholders. That starts with listening.

**Comment by xELFHEROx** [comment]
> I have made clear that force of wind is not something that I am interested in. Further, I have made clear that proportional RPM to wind speed is not correct. 
> 
> 
> 
> As an engineer, your job is to understand the expectations of your stakeholders. That starts with listening. 
> 
> 

Alright I understand now that the force of wind is not wanted in the simulation. However, as I have outlined in my Signoff and on the research I have done, without significantly manipulating the entire system environment with ducts or other large/long enclosures so that the CFM can be converted to mph, or without having the fans to test physically with an anemometer, I don't have a way to calculate or get an accurate measurement of what they wind speed from the fans would be. I would very much like any sort of advice or suggestions that you may have based on prior knowledge or any ideas you may have for this. But through my research this was the best method I could come up so any suggestions would be of great value. Thank you.

**Comment by xELFHEROx** [comment]
> I have made clear that force of wind is not something that I am interested in. Further, I have made clear that proportional RPM to wind speed is not correct.
> 
> As an engineer, your job is to understand the expectations of your stakeholders. That starts with listening.



> "When you are riding out on a physical trail, the movement of the air around you does not start to speed up." - Incorrect.
> 
> The air around you is considered stationary. You are moving. Therefore, the air around you has a speed equal to your velocity if measured from your reference frame. Changing your velocity results in an apparent change in wind speed.

What I meant by this is the change in wind speed is not a result of the air suddenly changing its movements and coming at you at a different speed, the wind speed is a result of the object going to into the air and the stationary air resulting in the equivalent wind speed going back at you.

**Review by JesseTNRoberts — COMMENTED** [review]
We need a citation for the formula and the constraints need to give the minimum fan speed necessary to do the task.

**Pull request merged**
