### PR TITLE
Team5-Signoff-Audio

### PR DESCRIPTION
**Pull request by Baebel43**
Requesting Signoff for Audio Subsystem

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
Not a markdown file.

**Comment by Baebel43** [comment]
Apologies for this mistake.

**Review by JesseTNRoberts — COMMENTED** [review]
I'm confused. I don't see a schematic for the circuit?

**Review by JesseTNRoberts — COMMENTED** [review]
Should the audio processing unit not be here?

**Comment by JesseBrewster** [comment]
Requesting Signoff for updated Audio Subsystem

**Review by JesseTNRoberts — COMMENTED** [review]
Are there not other devices connected to this microcontroller? If so, this needs to be added to the larger schematic.

why is there a speaker in the BOM? I see know schematic for the speaker.

**Comment by JesseBrewster** [comment]
I made the changes requested. Just let me know if anything else needs changed. Otherwise, requesting signoff.

**Review by JesseTNRoberts — COMMENTED** [review]
How do you know that the speaker can achieve the required volume beyond not overdoing it? 

Also, how do you know that the microphone will work plugged up in the manner decpicted?

**Comment by JesseBrewster** [comment]
Answered the questions from the previous commit and updated schematics/diagrams. Requesting Signoff.

**Pull request merged**
