### PR TITLE
Team5-sighnoff-Video

### PR DESCRIPTION
**Pull request by Baebel43**
Requesting Signoff for video subsystem

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
Constraints are ambiguous and insufficient.

**Comment by Strychn9na** [comment]
Requesting signoff for Revision 1 of the Video Subsystem

**Review by JesseTNRoberts — COMMENTED** [review]
There's no electrical schematic?

**Review by JesseTNRoberts — COMMENTED** [review]
I didn't see anything about the playback method.

**Comment by Strychn9na** [comment]
Requesting Signoff for Video Subsystem

**Review by JesseTNRoberts — COMMENTED** [review]
I still don't see how this addresses my previous feedback.

**Comment by Strychn9na** [comment]
Can you clarify exactly what you mean by playback method?

**Comment by Strychn9na** [comment]
I apologize if I am not understanding, but my understanding from your feedback about the playback method is what software we will be using to replay the video back to the user. I have added a line about Windows Media Player and how I will utilize it in the same way I was intending to with OBS.

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
